project = 'LibClock - Tamriel Standard Time'
format = 'discount'
file = 'Lib/LibClockTST.lua'
dir = 'doc'
all = true
readme = "README.md"
title = "LibClockTST Documentation"
description = "Libarary to make functions public to get information about the in-game time, date and moon. You can call them directly or subscribe to updates. Each function also gives the option to get information about a specific timestamp."